### ISSUE TITLE
No module named 'flask'

### ISSUE THREAD

**Issue by Acutapugione** [phusion/passenger-python-flask-demo#2]
/usr/share/passenger/helper-scripts/wsgi-loader.py:26: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import sys, os, re, imp, threading, signal, traceback, socket, select, struct, logging, errno
Traceback (most recent call last):
  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 369, in <module>
    app_module = load_app()
  File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 76, in load_app
    return imp.load_source('passenger_wsgi', startup_file)
  File "/usr/lib/python3.9/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/power_flask/powerhome_flask/passenger_wsgi.py", line 1, in <module>
    from app import app as application
  File "/var/www/power_flask/powerhome_flask/app/__init__.py", line 3, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'

**Comment by owenwu811** [comment]
pip install flask
